version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db

  app:
    container_name: app-dev
    image: app-dev
    build:
      context: ./ui
      target: development
    volumes:
      - ./ui/src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    container_name: app-back
    image: app-back
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000



